### ISSUE TITLE
seeking feedback on maintenance of original `connection` library

### ISSUE THREAD

**Issue by peterbecich** [kazu-yamamoto/crypton-connection#1]
Hello, I noticed you are working on a fork of `connection` in the Network Graph: https://github.com/vincenthz/hs-connection/network

I am seeking feedback on how the original archived library can be maintained, and would appreciate your input: https://discourse.haskell.org/t/fork-of-archived-connection-a-k-a-hs-connection-library/8545

Thank you

**Comment by Vlix** [comment]
I can tell you Vincent Hanquez has responded to that question before and said he will never transfer ownership and he will never continue working on the libraries.
Basically, anything Vincent Hanquez has made for Haskell is a legacy library that will not change anymore.

He also said that anyone can fork a repo and make a new library (this is how and why Kazu forked `cryptonite` and published `crypton`). So if you'd like to "take over maintainership", you can do so whenever you want. The library just can't be called `connection` 👍

**Comment by peterbecich** [comment]
Thanks @Vlix, I was unaware of this. I see now `crypton-connection` is already on Hackage: https://hackage.haskell.org/package/crypton-connection
I  will focus on using that.

**Comment by kazu-yamamoto** [comment]
I gave the `crypton` prefix to all forked libraries.
I hope they all will be deprecated in the near future.
One hope is here: https://github.com/haskellfoundation/tech-proposals/pull/57
